export const MENU_KEYS = {
  DASHBOARD: "DASHBOARD",
  CONFIG_USUARIOS: "CONFIG_USUARIOS",
  CONFIG_ROLES: "CONFIG_ROLES",
  CONFIG_GENERAL: "CONFIG_GENERAL",
  CONFIG_MENU: "CONFIG_MENU",
  POS_PERIPHERALS: "POS_PERIPHERALS",
  INVENTORY_PROMOTIONS: "INVENTORY_PROMOTIONS",
  ELECTRONIC_INVOICING_CUSTOMERS: "ELECTRONIC_INVOICING_CUSTOMERS",
  ELECTRONIC_INVOICING_SUPPLIERS: "ELECTRONIC_INVOICING_SUPPLIERS",
} as const;

export const MENU_KEY_ALIASES: Record<string, string[]> = {
  [MENU_KEYS.DASHBOARD]: ["DASHBOARD_TENANT_DASHBOARD"],
  [MENU_KEYS.CONFIG_USUARIOS]: ["USUARIOS_TENANT_USUARIOS"],
  [MENU_KEYS.CONFIG_ROLES]: ["ROLES_TENANT_ROLES"],
  [MENU_KEYS.CONFIG_GENERAL]: ["CONFIGURACION_TENANT_CONFIGURACION"],
  [MENU_KEYS.CONFIG_MENU]: ["CONFIGURACION_TENANT_CONFIGURACION_MENU"],
  [MENU_KEYS.POS_PERIPHERALS]: [],
};

export const getMenuKeyCandidates = (menuKey: string): string[] => {
  const candidates = new Set<string>([menuKey, ...(MENU_KEY_ALIASES[menuKey] ?? [])]);

  for (const [canonicalKey, aliases] of Object.entries(MENU_KEY_ALIASES)) {
    if (aliases.includes(menuKey)) {
      candidates.add(canonicalKey);
    }
  }

  return Array.from(candidates);
};
