export type {
  DownloadElectronicDocumentAttachmentCommand,
  ElectronicBillingEnvironment,
  ElectronicBillingProviderAttachmentResult,
  ElectronicBillingProviderCapabilities,
  ElectronicBillingProviderContext,
  ElectronicBillingProviderDocumentResult,
  ElectronicBillingProviderOperationsResult,
  ElectronicBillingProviderStatusResult,
  ElectronicCreditNoteReason,
  ElectronicCustomer,
  ElectronicCustomerIdentification,
  ElectronicDocumentIssueBaseCommand,
  ElectronicDocumentLineInput,
  ElectronicDocumentTotals,
  ElectronicOriginalDocumentReference,
  ElectronicPayment,
  ElectronicTaxInput,
  GetElectronicDocumentStatusCommand,
  IssueElectronicCreditNoteCommand,
  IssueElectronicInvoiceCommand,
  ResolveElectronicBillingProviderCommand,
  ResolvedElectronicBillingProviderConfig,
  RetryElectronicDocumentCommand,
} from "../domain/electronic-billing.types";
