export const MENU_KEYS = {
  DASHBOARD: "DASHBOARD",
  CONFIG_USUARIOS: "CONFIG_USUARIOS",
  CONFIG_ROLES: "CONFIG_ROLES",
  CONFIG_GENERAL: "CONFIG_GENERAL",
  CONFIG_MENU: "CONFIG_MENU",
  CONFIG_TERMINALS: "CONFIG_TERMINALS",
  POS_PERIPHERALS: "POS_PERIPHERALS",
  INVENTORY_PRODUCTS: "INVENTORY_PRODUCTS",
  INVENTORY_LOCATIONS: "INVENTORY_LOCATIONS",
  INVENTORY_LOTS: "INVENTORY_LOTS",
  INVENTORY_UNITS: "INVENTORY_UNITS",
  INVENTORY_TAXES: "INVENTORY_TAXES",
  INVENTORY_PURCHASES: "INVENTORY_PURCHASES",
  INVENTORY_SUPPLIERS: "INVENTORY_SUPPLIERS",
  INVENTORY_PROMOTIONS: "INVENTORY_PROMOTIONS",
  ORDERS: "ORDERS",
  CUSTOMERS: "CUSTOMERS",
} as const;

export const MENU_KEY_ALIASES: Record<string, string[]> = {
  [MENU_KEYS.DASHBOARD]: ["DASHBOARD_TENANT_DASHBOARD"],
  [MENU_KEYS.CONFIG_USUARIOS]: ["USUARIOS_TENANT_USUARIOS"],
  [MENU_KEYS.CONFIG_ROLES]: ["ROLES_TENANT_ROLES"],
  [MENU_KEYS.CONFIG_GENERAL]: ["CONFIGURACION_TENANT_CONFIGURACION"],
  [MENU_KEYS.CONFIG_MENU]: ["CONFIGURACION_TENANT_CONFIGURACION_MENU"],
  [MENU_KEYS.CONFIG_TERMINALS]: [],
  [MENU_KEYS.POS_PERIPHERALS]: [],
  [MENU_KEYS.INVENTORY_PRODUCTS]: [],
  [MENU_KEYS.INVENTORY_LOCATIONS]: [],
  [MENU_KEYS.INVENTORY_LOTS]: [],
  [MENU_KEYS.INVENTORY_UNITS]: [],
  [MENU_KEYS.INVENTORY_TAXES]: [],
  [MENU_KEYS.INVENTORY_PURCHASES]: [],
  [MENU_KEYS.INVENTORY_SUPPLIERS]: [],
  [MENU_KEYS.INVENTORY_PROMOTIONS]: [],
  [MENU_KEYS.ORDERS]: [],
  [MENU_KEYS.CUSTOMERS]: [],
};

export const getMenuKeyCandidates = (menuKey: string): string[] => {
  const candidates = new Set<string>([menuKey, ...(MENU_KEY_ALIASES[menuKey] ?? [])]);

  for (const [canonicalKey, aliases] of Object.entries(MENU_KEY_ALIASES)) {
    if (aliases.includes(menuKey)) {
      candidates.add(canonicalKey);
    }
  }

  return Array.from(candidates);
};
