import assert from "node:assert/strict";
import test from "node:test";
import { TerminalReadinessOrchestrator } from "./orchestrator";

const setWindow = (manusTerminal: unknown) => Object.defineProperty(globalThis, "window", { configurable: true, value: { manusTerminal } });
const info = { electronRuntimeVersion: "0.1.0", bridgeContractVersion: 1, agentApiVersion: 1, capabilities: ["agent.health"] };
const healthy = (id = "install-a") => ({ getRuntimeInfo: async () => info, getAgentHealth: async () => ({ status: "ok", agentInstallationId: id, version: "1.0.0" }) });
const cloud = async (payload: unknown, run: () => Promise<void>) => { const old = globalThis.fetch; let body = ""; globalThis.fetch = async (_input, init) => { body = String(init?.body); return new Response(JSON.stringify(payload), { status: 200, headers: { "content-type": "application/json" } }); }; try { await run(); } finally { globalThis.fetch = old; } assert.equal(body.includes("tenantId"), false); };

test("WEB mode stays allowed and does not call runtime resolution", async () => { setWindow(undefined); let called = false; const old = globalThis.fetch; globalThis.fetch = async () => { called = true; throw new Error(); }; try { const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.mode, value.state, value.canEnterPos], ["WEB", "READY", true]); assert.equal(called, false); } finally { globalThis.fetch = old; } });
test("configured Electron runtime is READY", async () => { setWindow(healthy()); await cloud({ resolution: "CONFIGURED", deviceStatus: "BOUND", terminal: { terminalId: "terminal-a", branchId: "branch-a", active: true } }, async () => { const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.state, value.canEnterPos, value.terminal.terminalId], ["READY", true, "terminal-a"]); }); });
test("cold Agent outage blocks Electron entry without identity", async () => { setWindow({ getRuntimeInfo: async () => ({ ...info, agentApiVersion: null }), getAgentHealth: async () => ({ available: false }) }); const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.state, value.reason, value.canEnterPos], ["DEGRADED", "AGENT_UNAVAILABLE", false]); });
test("post-ready Agent outage uses volatile identity and stays degraded-allowed", async () => { const runtime = new TerminalReadinessOrchestrator(); setWindow(healthy()); await cloud({ resolution: "CONFIGURED", deviceStatus: "BOUND", terminal: { terminalId: "terminal-a", branchId: "branch-a", active: true } }, async () => { assert.equal((await runtime.evaluate({ authenticated: true })).state, "READY"); }); setWindow({ getRuntimeInfo: async () => ({ ...info, agentApiVersion: null }), getAgentHealth: async () => ({ available: false }) }); await cloud({ resolution: "CONFIGURED", deviceStatus: "BOUND", terminal: { terminalId: "terminal-a", branchId: "branch-a", active: true } }, async () => { const value = await runtime.evaluate({ authenticated: true }); assert.deepEqual([value.state, value.reason, value.canEnterPos], ["DEGRADED", "AGENT_UNAVAILABLE", true]); }); });
test("recreated orchestrator loses volatile identity", async () => { setWindow({ getRuntimeInfo: async () => ({ ...info, agentApiVersion: null }), getAgentHealth: async () => ({ available: false }) }); const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.state, value.canEnterPos], ["DEGRADED", false]); });
test("resolution outcomes and auth are bounded", async () => { setWindow(healthy()); for (const resolution of ["DEVICE_UNKNOWN", "DEVICE_UNBOUND", "DEVICE_REVOKED", "TERMINAL_UNKNOWN", "TERMINAL_DISABLED"] as const) await cloud({ resolution }, async () => { const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.state, value.reason, value.canEnterPos], ["NOT_CONFIGURED", resolution, false]); }); const old = globalThis.fetch; let called = false; globalThis.fetch = async () => { called = true; throw new Error(); }; try { const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: false }); assert.deepEqual([value.state, value.reason, value.canEnterPos], ["BOOTING", "AUTH_REQUIRED", false]); assert.equal(called, false); } finally { globalThis.fetch = old; } });
test("unsupported bridge is incompatible", async () => { setWindow({ getRuntimeInfo: async () => ({ ...info, bridgeContractVersion: 2 }), getAgentHealth: async () => ({ available: false }) }); const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.state, value.reason, value.canEnterPos], ["INCOMPATIBLE", "BRIDGE_CONTRACT_UNSUPPORTED", false]); });
test("unsupported Agent API is incompatible for physical runtime", async () => { setWindow({ getRuntimeInfo: async () => ({ ...info, agentApiVersion: 2 }), getAgentHealth: async () => ({ available: true, agentInstallationId: "install-a" }) }); const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.state, value.reason, value.canEnterPos], ["INCOMPATIBLE", "AGENT_API_UNSUPPORTED", false]); });
test("bound Terminal must match existing POS session Terminal", async () => { setWindow(healthy()); await cloud({ resolution: "CONFIGURED", deviceStatus: "BOUND", terminal: { terminalId: "terminal-a", branchId: "branch-a", active: true } }, async () => { const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true, posTerminalId: "terminal-b" }); assert.deepEqual([value.state, value.reason, value.canEnterPos], ["NOT_CONFIGURED", "TERMINAL_CONTEXT_MISMATCH", false]); }); });
test("no POS session does not create a false context mismatch", async () => { setWindow(healthy()); await cloud({ resolution: "CONFIGURED", deviceStatus: "BOUND", terminal: { terminalId: "terminal-a", branchId: "branch-a", active: true } }, async () => { const value = await new TerminalReadinessOrchestrator().evaluate({ authenticated: true }); assert.deepEqual([value.state, value.canEnterPos], ["READY", true]); }); });
test("cloud failure blocks and explicit retry re-evaluates", async () => { setWindow(healthy()); const old = globalThis.fetch; let attempts = 0; globalThis.fetch = async () => { attempts += 1; if (attempts === 1) throw new Error("cloud down"); return new Response(JSON.stringify({ resolution: "CONFIGURED", deviceStatus: "BOUND", terminal: { terminalId: "terminal-a", branchId: "branch-a", active: true } }), { status: 200, headers: { "content-type": "application/json" } }); }; try { const runtime = new TerminalReadinessOrchestrator(); const blocked = await runtime.evaluate({ authenticated: true }); assert.deepEqual([blocked.state, blocked.reason, blocked.canEnterPos], ["CLOUD_UNAVAILABLE", "CLOUD_UNAVAILABLE", false]); const recovered = await runtime.refresh({ authenticated: true }); assert.deepEqual([recovered.state, recovered.canEnterPos], ["READY", true]); assert.equal(attempts, 2); } finally { globalThis.fetch = old; } });
