import type { RuntimeCompatibility } from "../peripherals/runtime-contract";
import { resolveTerminalRuntime } from "./cloud-runtime";
import { collectLocalRuntime } from "./local-runtime";
import type { LocalRuntimeSnapshot, ReadinessReason, TerminalReadinessResult, TerminalRuntimeResolution } from "./contracts";
export type EvaluationInput = { authenticated: boolean; posTerminalId?: string | null };
const makeResult = (local: LocalRuntimeSnapshot, input: EvaluationInput, state: TerminalReadinessResult["state"], reason: ReadinessReason, canEnterPos: boolean, terminalId: string | null = null, branchId: string | null = null, deviceStatus: TerminalReadinessResult["device"]["status"] = null): TerminalReadinessResult => ({ mode: local.mode, state, reason, canEnterPos, localRuntime: local, agent: local.agent, cloud: { reachable: false, authenticated: input.authenticated }, device: { status: deviceStatus }, terminal: { terminalId, branchId, active: terminalId ? true : null } });
const mapIncompatibility = (value: RuntimeCompatibility): ReadinessReason => value.info?.agentApiVersion !== null && value.info?.agentApiVersion !== undefined && value.info.agentApiVersion !== 1 ? "AGENT_API_UNSUPPORTED" : value.reason === "UNSUPPORTED_CONTRACT" ? "BRIDGE_CONTRACT_UNSUPPORTED" : value.reason === "INVALID_METADATA" ? "METADATA_INVALID" : "BRIDGE_UNAVAILABLE";
const mapResolution = (local: LocalRuntimeSnapshot, input: EvaluationInput, resolution: TerminalRuntimeResolution, degraded: boolean, reason: ReadinessReason): TerminalReadinessResult => {
  if (resolution.resolution !== "CONFIGURED") return makeResult(local, input, "NOT_CONFIGURED", resolution.resolution, false);
  if (input.posTerminalId && input.posTerminalId !== resolution.terminal.terminalId) return makeResult(local, input, "NOT_CONFIGURED", "TERMINAL_CONTEXT_MISMATCH", false, resolution.terminal.terminalId, resolution.terminal.branchId, "BOUND");
  return makeResult(local, input, degraded ? "DEGRADED" : "READY", degraded ? reason : "CHECKING", true, resolution.terminal.terminalId, resolution.terminal.branchId, "BOUND");
};
export class TerminalReadinessOrchestrator { private volatileInstallationId: string | null = null; async evaluate(input: EvaluationInput): Promise<TerminalReadinessResult> { const probe = await collectLocalRuntime(); const { snapshot, compatibility, installationId } = probe; if (snapshot.mode === "WEB") return makeResult(snapshot, input, input.authenticated ? "READY" : "BOOTING", input.authenticated ? "CHECKING" : "AUTH_REQUIRED", true); if (compatibility?.state === "INCOMPATIBLE") return makeResult(snapshot, input, "INCOMPATIBLE", mapIncompatibility(compatibility), false); if (compatibility?.reason === "LEGACY_BRIDGE") return makeResult(snapshot, input, "DEGRADED", "BRIDGE_LEGACY", false); if (!input.authenticated) return makeResult(snapshot, input, "BOOTING", "AUTH_REQUIRED", false); if (installationId) this.volatileInstallationId = installationId; const identity = installationId ?? this.volatileInstallationId; if (!identity) return makeResult(snapshot, input, snapshot.agent.reachable ? "NOT_CONFIGURED" : "DEGRADED", snapshot.agent.reachable ? "INSTALLATION_ID_UNAVAILABLE" : "AGENT_UNAVAILABLE", false); let resolution: TerminalRuntimeResolution; try { resolution = await resolveTerminalRuntime(identity); } catch { return makeResult(snapshot, input, "CLOUD_UNAVAILABLE", "CLOUD_UNAVAILABLE", false); } const reason: ReadinessReason = !snapshot.agent.reachable ? "AGENT_UNAVAILABLE" : compatibility?.reason === "AGENT_UNKNOWN" ? "AGENT_API_UNKNOWN" : "AGENT_UNAVAILABLE"; return mapResolution(snapshot, input, resolution, !snapshot.agent.reachable, reason); } refresh(input: EvaluationInput) { return this.evaluate(input); } }
export const createTerminalReadinessOrchestrator = () => new TerminalReadinessOrchestrator();
